### ISSUE TITLE
What is the purpose of certbot role in docker swarm collection? 

### ISSUE THREAD

**Issue by ieugen** [JoelLefkowitz/swarmroles#1]
Hi,

Nice collection of roles. 
I am curios about Certbot role - it seems out of place to me.
Could you please explain / document what is it's purpose?

Thanks,
Eugen

**Comment by JoelLefkowitz** [comment]
When deploying a webapp to a swarm I often have an nginx service that exposes an https endpoint.
In the docker-compose file I bind the certificate on the swarm node to the service.

volumes:
  - type: bind
    source: /etc/letsencrypt/live/joellefkowitz.co.uk/fullchain.pem
    target: /etc/nginx/joellefkowitz.co.uk.crt
  - type: bind
    source: /etc/letsencrypt/live/joellefkowitz.co.uk/privkey.pem
    target: /etc/nginx/joellefkowitz.co.uk.key

So in the same way that pulling images and copying necessary files must happen on every manager node, we may also need to fetch certificates from an external source so that the services have everything they need in order to launch.

I will add this to the swarmroles/certbot docs, does that explain it more clearly?
Joel

**Comment by ieugen** [comment]
Yes, thanks for clarifying. 

I usually deploy traefik with docker swarm as an ingress controller. 
I use docker labels to expose services in the swarm outside.
This setup works much better for me when using swarm since the services are exposed dynamically using labels (+ automated certificates).

The way I organize things is:
- collection to have docker swarm up and running and configure it.
- collections to deploy apps and services on top of any swarm

Following the above logic I would keep this role in another collection so they can evolve at their own pace.

**Comment by JoelLefkowitz** [comment]
I'm moving certbot to another repo for all swamroles support addons
